// This file is generated by scripts/build-mdx-index.ts
// Do not edit manually. This index contains metadata only (no MDX imports).

export type MDXMeta = { title?: string; description?: string; [key: string]: any }

export const MDX_PAGES: { [slug: string]: { meta: MDXMeta } } = {
  example: { meta: { title: 'Example Landing', description: 'A minimal example landing page for static export.' } },
} as const

export type MDXSlug = keyof typeof MDX_PAGES
