// This file is generated by scripts/build-mdx-index.cjs
// Do not edit manually.

import Component0 from './example.mdx'
import * as Meta0 from './example.mdx'

export type MDXMeta = { title?: string; description?: string; [key: string]: any }

export const MDX_PAGES = {
  'example': { Component: Component0, meta: Meta0 as MDXMeta },
} as const

export type MDXSlug = keyof typeof MDX_PAGES
