// This file is generated by scripts/build-mdx-index.js
// Do not edit manually.

import Component0 from './example.mdx'
import * as Meta0 from './example.mdx'

export const MDX_PAGES = {
  'example': { Component: Component0, meta: Meta0 as any },
} as const
